all:
	g++ -g -Wall -std=c++11 -o template1 template1_lib.cpp template1_app.cpp
	g++ -g -Wall -std=c++11 -o template2 template2_lib.cpp template2_app.cpp

clean:
	del  template1.exe template2.exe   # Windows
# rm -rf template1 template2       # Linux